name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # Allow manual trigger
  workflow_dispatch:
  # Update when pushing to master
  push: { branches: ["master"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: hexpreso
          template: classic
          filename: metrics.svg

          # Base info
          base: header
          repositories_forks: no

          # GitHub Skyline plugin (3D commit visualization)
          plugin_skyline: yes
          plugin_skyline_year: current
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5

          # Languages plugin (recently used with indepth analysis)
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
