name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # Allow manual trigger
  workflow_dispatch:
  # Update when pushing to master
  push: { branches: ["master"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: hexpreso
          template: classic
          filename: metrics.svg

          # Base info
          base: header
          repositories_forks: no

          # Isocalendar plugin (yearly commit grid)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages plugin (indepth analysis)
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
